version: '3.8'
services:
  paytm:
    image: subhojit840/paytm:latest
    ports:
      - "91:80"
    deploy:
      replicas: 2
  netflix:
    image: subhojit840/netflix:latest
    ports:
      - "92:80"
    deploy:
      replicas: 2
