version: '3.8'
services:
  movies:
    image: subhojit840/movies:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
  train:
    image: subhojit840/dth:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
  recharge:
    image: subhojit840/recharge:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
  dth:
    image: subhojit840/payment:latest
    ports:
      - "94:80"
    deploy:
      replicas: 3
